// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportCsv(arg1) {
  return window['go']['main']['App']['ImportCsv'](arg1);
}

export function ImportExcel(arg1) {
  return window['go']['main']['App']['ImportExcel'](arg1);
}

export function LookUpPath(arg1) {
  return window['go']['main']['App']['LookUpPath'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}
