// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function LookUpPath(arg1:string):Promise<Array<string>>;

export function RunCommand(arg1:string):Promise<string>;
